name: Publish with VSCE
on:
  pull_request:
    types: [assigned]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm install -g vsce
    - name: vsce publish 
      run: vsce publish -p "${{ secrets.VSCE_TOKEN }}"
