name: Deploy Extension
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install vsce
        run: |
          npm install
          npm install --global @vscode/vsce

      - name: Publish
        run: vsce publish -p ${{ secrets.VSCE_TOKEN }}
